[package]
name = "code-scout"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }  # For CLI options
ignore = "0.4"